# Generated by scripts/generate-brewfile.sh
# Edit dot_config/mise/config/shared.yaml or host.yaml instead

# Shared tools (also managed by mise in devcontainers)
brew "bat"
brew "git-delta"
brew "fd"
brew "hadolint"
brew "jq"
brew "lazygit"
brew "neovim"
brew "node"
brew "ripgrep"
brew "ruff"
brew "shfmt"
brew "starship"
brew "stylua"
brew "tflint"
brew "yq"
brew "zoxide"

# Host-only formulas
brew "anacron"
brew "btop"
brew "cloud-nuke"
brew "podman"
brew "sesh"
brew "television"
brew "tldr"
brew "tmux"
brew "tree"
brew "vhs"
brew "visidata"

# Apps
cask "1password"
cask "claude-code"
cask "devpod"
cask "ghostty"
cask "google-cloud-sdk"
cask "nikitabobko/tap/aerospace"
cask "obsidian"
cask "spotify"
