# Generated from tools.yaml — do not edit directly

# Shared tools (also managed by mise in devcontainers)
brew "bat"
brew "git-delta"
brew "fd"
brew "gh"
brew "hadolint"
brew "helm"
brew "jq"
brew "kubectl"
brew "kustomize"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "ruff"
brew "shfmt"
brew "starship"
brew "stylua"
brew "television"
brew "tflint"
brew "yq"
brew "zoxide"

# Host-only formulas
brew "btop"
brew "node"
brew "cloud-nuke"
brew "fluxcd/tap/flux"
brew "go"
brew "k9s"
brew "kubectl"
brew "podman"
brew "sesh"
brew "siderolabs/tap/sidero-tools"
brew "tldr"
brew "tmux"
brew "tree"
brew "vhs"
brew "visidata"

# Apps
cask "1password"
cask "aerospace"
cask "claude-code"
cask "devpod"
cask "ghostty"
cask "google-cloud-sdk"
cask "obsidian"
cask "spotify"
