#!/usr/bin/env bash

set -eou pipefail

echo "[START] installing chezmoi"
sh -c "$(curl -fsLS get.chezmoi.io)" \
    -- init --apply https://github.com/bear-jordan/dotfiles.git
rm -rf bin/
echo "[END  ] installing chezmoi"

echo "[START] installing mise"
curl https://mise.run/bash | sh
echo "[END  ] installing mise"

exit 0
