#!/usr/bin/env bash

set -eou pipefail

echo "[START] installing chezmoi"
sh -c "$(curl -fsLS get.chezmoi.io)" \
    -- init --apply https://github.com/bear-jordan/dotfiles.git
rm -rf bin/
echo "[END  ] installing chezmoi"

echo "[START] installing mise"
curl https://mise.run/bash | sh
echo "[END  ] installing mise"

echo "[START] installing devpod"
curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && sudo install -c -m 0755 devpod /usr/local/bin && rm -f devpod
echo "[END  ] installing devpod"

exit 0
