[tools]
# Shell utilities
btop = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
rg = "latest"
starship = "latest"
zoxide = "latest"

# Editor
neovim = "latest"

# LSP servers
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:pyright" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
lazygit = "latest"
lua-language-server = "latest"
terraform-ls = "latest"

# Formatters
"npm:prettier" = "latest"
ruff = "latest"
shfmt = "latest"
stylua = "latest"

# Linters
sqlfluff = "latest"
tflint = "latest"
