formulas:
  - btop
  - cloud-nuke
  - podman
  - sesh
  - go
  - tldr
  - tmux
  - tree
  - vhs
  - visidata
  - fluxcd/tap/flux
  - kubectl
  - siderolabs/tap/sidero-tools
  - k9s

casks:
  - 1password
  - claude-code
  - devpod
  - ghostty
  - gcloud-cli
  - nikitabobko/tap/aerospace
  - obsidian
  - spotify
