tools:
  # Shell utilities (also in Brewfile)
  bat: latest
  delta: latest
  fd: latest
  gh: latest
  jq: latest
  lazygit: latest
  neovim: latest
  node: latest
  rg: latest
  starship: latest
  yq: latest
  zoxide: latest

  # Formatters (also in Brewfile)
  ruff: latest
  shfmt: latest
  stylua: latest

  # Linters (also in Brewfile)
  hadolint: latest
  tflint: latest
