#!/usr/bin/env bash
set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$DOTFILES_DIR/dot_config/mise/config"
OUTPUT="$DOTFILES_DIR/Brewfile"

brew_name() {
    case "$1" in
        delta) echo "git-delta" ;;
        rg)    echo "ripgrep" ;;
        *)     echo "$1" ;;
    esac
}

{
    echo "# Generated by scripts/generate-brewfile.sh"
    echo "# Edit dot_config/mise/config/shared.yaml or host.yaml instead"
    echo ""

    echo "# Shared tools (also managed by mise in devcontainers)"
    yq '.tools | keys | .[]' "$CONFIG_DIR/shared.yaml" | sort | while read -r tool; do
        echo "brew \"$(brew_name "$tool")\""
    done

    echo ""
    echo "# Host-only formulas"
    yq '.formulas[]' "$CONFIG_DIR/host.yaml" | while read -r formula; do
        echo "brew \"$formula\""
    done

    echo ""
    echo "# Apps"
    yq '.casks[]' "$CONFIG_DIR/host.yaml" | while read -r cask; do
        echo "cask \"$cask\""
    done
} > "$OUTPUT"

echo "Brewfile written to $OUTPUT"
