contexts:
  default:
    defaultProvider: docker
    defaultIde: none
    options:
      DOTFILES_SCRIPT:
        value: install.sh
      DOTFILES_URL:
        userProvided: true
        value: git@github.com:bear-jordan/dotfiles
    providers:
      docker:
        creationTimestamp: "2026-04-25T23:15:15Z"
        initialized: true
        options:
          DOCKER_BUILDER: {}
          DOCKER_HOST: {}
          DOCKER_PATH:
            value: podman
          INACTIVITY_TIMEOUT: {}
defaultContext: default

