[tools]
"asdf:neovim" = "nightly"
aws = "latest"
bat = "latest"
chezmoi = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
opencode = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"
